version: '3'

volumes:
  # A volume to store mopify data in a persitent way.
  mopidy_data:

services:
  mopidy:
    image: audiostation/mopidy:latest
    ports:
      - "6600:6600"
      - "6680:6680"
      - "5555:5555"
    depends_on:
      - snapserver
    volumes:
      # The volume with the sharesound fifo for snapcast to work
      - /tmp/sharesound:/tmp/sharesound
      # A config of mopidy that pipes audio into the snapfifo
      - ./mopidy.conf:/etc/mopidy/mopidy.conf:ro
      - mopidy_data:/var/lib/mopidy
    restart: unless-stopped

  snapserver:
    image: audiostation/snapcast:latest
    volumes:
      # The volume with the sharesound fifo for snapcast to work
      - /tmp/sharesound:/tmp/sharesound
    command: "snapserver -s pipe:///tmp/sharesound/snapfifo?name=Radio"
    # host mode is needed for snapserver advertisement
    network_mode: "host"
    restart: unless-stopped

  spotify:
    image: audiostation/spotify:latest
    # host mode is needed for Spotifyd advertisement
    network_mode: "host"
    depends_on:
      - snapserver
    volumes:
      # The volume with the sharesound fifo for snapcast to work
      - /tmp/sharesound:/tmp/sharesound
    restart: unless-stopped

  upmpdcli:
    image: audiostation/upmpdcli:latest
    command: "-h mopidy -f Audiostation"
    depends_on:
      - mopidy
    # Host mode needed for advertisement
    network_mode: "host"

  # Not working
  #airplay:
  #  image: audiostation/airplay:1.0
  #  network_mode: "host"
  #  depends_on:
  #    - snapserver
  #  restart: unless-stopped
  #  volumes:
  #    #- ./shairport-sync.conf:/etc/shairport-sync.conf:ro
  #    - /tmp/sharesound:/tmp/sharesound


  # Turn this on if you have no other snapcast client on the server
  #snapclient:
  #  image: audiostation/snapcast:latest
  #  links:
  #   - snapserver:snapserverhost
  #  depends_on:
  #    - snapserver
  #  devices:
  #   - "/dev/snd/:/dev/snd/"
  #  command: "snapclient -h snapserver"
  #  restart: unless-stopped
